### ISSUE TITLE
Re-arrange the columns from the table

### ISSUE THREAD

**Issue by luiscape** [luiscape/hdxscraper-wfp-vam-api#5]
The order should be the order of what is in the Excel file attached.

The order should be:
```
FCS_id  ADM0_ID ADM1_ID ADM2_ID ADM3_ID ADM4_ID ADM5_ID FCS_mean  FCS_poor  FCS_borderline  FCS_acceptable  targetGroupID FCS_month FCS_year  FCS_dataSource  Lz_ID FCS_lowerThreshold  FCS_upperThreshold  methodologyID IndicatorTypeID mr_id
```

**Comment by reubano** [comment]
Just cross referenced this with the current list and this list is missing the following fields:

```python
['LivelihoodZoneName', 'Methodology', 'TargetGroup']
```

What should happen to them?

**Comment by luiscape** [comment]
The order should follow the same order of the respective files added by WFP: 

* https://data.hdx.rwlabs.org/dataset/coping-strategy-index-csi
* https://data.hdx.rwlabs.org/dataset/food-consumption-score-fcs
* https://data.hdx.rwlabs.org/dataset/income-activitie

**Comment by luiscape** [comment]
Hi @reubano, I can see a commit on this issue. Can I close it?

**Comment by reubano** [comment]
Sure thing.

**Comment by luiscape** [comment]
Nice.
